[package]
name = "currencyapi"
version = "0.2.0"
description = "currencyapi API"
authors = ["Yehuthith <yehuthith@gmail.com>"]
repository = "https://github.com/yehuthi/currencyapi-rs"
license = "MIT OR Apache-2.0"
categories = ["api-bindings"]
keywords = ["currency", "convert", "freecurrencyapi", "money", "api"]
edition = "2021"

[dependencies]
atoi = "2.0.0"
bstringify = "0.1.2"
chrono = "0.4.21"
reqwest = { version = "0.11.11", features = ["json"] }
serde_json = "1.0.83"
smallstr = { version = "0.3.0", features = ["serde", "union"] }
smallvec = { version = "1.9.0", features = ["serde", "union", "const_generics", "const_new"] }
thiserror = "1.0.32"

[dev-dependencies]
clap = { version = "4.0.29", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
rust_decimal = "1.26.1"

[[example]]
name = "cli"
