[package]
name = "currencyapi"
version = "0.1.0"
description = "currencyapi API"
authors = ["Yehuthith <yehuthith@gmail.com>"]
license = "MIT OR Apache-2.0"
categories = ["api-bindings"]
keywords = ["currency", "convert", "freecurrencyapi", "money", "api"]
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
